name: Sync Examples

on:
  push:
    branches: [main]
    paths: ['pyproject.toml']
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync-examples:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install toml
        
    - name: Run sync script
      run: python scripts/sync_examples.py
      
    - name: Check for changes
      id: verify-changed-files
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "changed=true" >> $GITHUB_OUTPUT
        else
          echo "changed=false" >> $GITHUB_OUTPUT
        fi
        
    - name: Commit changes
      if: steps.verify-changed-files.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add examples/
        git commit -m "Auto-sync examples with pyproject.toml changes"
        git push
        
    - name: Create summary
      run: |
        echo "## Examples Sync Summary" >> $GITHUB_STEP_SUMMARY
        if [ "${{ steps.verify-changed-files.outputs.changed }}" == "true" ]; then
          echo "✅ Examples were updated and synchronized with pyproject.toml" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Changes made:" >> $GITHUB_STEP_SUMMARY
          echo "- Updated examples/requirements.txt with current dependencies" >> $GITHUB_STEP_SUMMARY
          echo "- Updated version references in example files" >> $GITHUB_STEP_SUMMARY
          echo "- Ensured examples stay compatible with package changes" >> $GITHUB_STEP_SUMMARY
        else
          echo "ℹ️ No changes needed - examples are already in sync" >> $GITHUB_STEP_SUMMARY
        fi
